version: "3.9"
services:
  recommend-api:
    build: .
    volumes:
      - type: bind
        source: /home/chuck/folder/trained_models
        target: /app/trained_models
    environment:
      - TZBACKEND_URL=http://192.168.1.20:8989/api
      - DELAY_IN_SECONDS=60
      - DEBUG=True
    ports:
      - "5000:5000"
